# 内网环境配置（使用CSP SDK）

adapter:
  provider:
    type: CSP_SDK
    enable-mock: false

# https 地址/内部地址
server:
  address: {mbase_ip}
  port: 8090

logging:
  file:
    name: /opt/logs/browsergw.log

browsergw:
  workspace: /opt/host
  chrome:
    headless: true
    record-mode: 1
    record-extension-id: majikpeglnhefidjkmpeipdbikkfbmho
    endpoint: http://127.0.0.1:8000
    executable-path: /usr/bin/chromium
    ttl: 360000000000 #ns 超过此时间无心跳的浏览器会被关闭
  # 上报到redis的信息，其中endpoint可能是外部地址
  report:
    cap: 300
    control-endpoint: {edge_control_extend_endpoint}
    media-endpoint: {edge_media_extend_endpoint}
    control-tls-endpoint: {edge_control_tls_extend_endpoint}
    media-tls-endpoint: {edge_media_tls_extend_endpoint}
    ttl: 120 # 过期时间
    chain-endpoints: {chain_endpoints}
  # socket信息
  websocket:
    media-port: 30002
    muen-port: 30005
    boss: 8
    worker: 64
    heartbeat-ttl: 300000 #ms 超过此时间无心跳的socket连接会被关闭
  # 定时任务周期
  scheduled:
    close-browser-period: 600000 #单位毫秒
    tcp-heartbeat-period: 600000 #单位毫秒
    check-browser-period: 600000 #单位毫秒
    report-period: 10000 #单位毫秒
    health-check-period: 60000
    session-report-period: 300000  #单位毫秒
    data-size-report-period: 300000  #单位毫秒
  # 本地tcp服务地址
  tcp:
    address: {sc_trunk_ip}
    control-port: {control_port}
    media-port: {media_port}
    control-tls-port: {control_tls_port}
    media-tls-port: {media_tls_port}
    heartbeat-ttl: 360000000000 #ns 超过此时间无心跳的tcp连接会被关闭
    enable-http: {enable_http}
  drop-frame-multi: 0.0
  context-limit: 20
  healthCheck:
    cpu-trigger-threshold: 90
    cpu-recover-threshold: 80
    memory-trigger-threshold: 90
    memory-recover-threshold: 80

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /actuator
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      group:
        liveness:
          include:
            - ping
        readiness:
          include:
            - redis
